// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: C2.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VictimStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host          string               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	LastHeardFrom *timestamp.Timestamp `protobuf:"bytes,2,opt,name=lastHeardFrom,proto3" json:"lastHeardFrom,omitempty"`
}

func (x *VictimStatus) Reset() {
	*x = VictimStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_C2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VictimStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VictimStatus) ProtoMessage() {}

func (x *VictimStatus) ProtoReflect() protoreflect.Message {
	mi := &file_C2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VictimStatus.ProtoReflect.Descriptor instead.
func (*VictimStatus) Descriptor() ([]byte, []int) {
	return file_C2_proto_rawDescGZIP(), []int{0}
}

func (x *VictimStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VictimStatus) GetLastHeardFrom() *timestamp.Timestamp {
	if x != nil {
		return x.LastHeardFrom
	}
	return nil
}

type C2Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MalwareId string               `protobuf:"bytes,1,opt,name=malwareId,proto3" json:"malwareId,omitempty"`
	Victims   []*VictimStatus      `protobuf:"bytes,2,rep,name=victims,proto3" json:"victims,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *C2Update) Reset() {
	*x = C2Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_C2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2Update) ProtoMessage() {}

func (x *C2Update) ProtoReflect() protoreflect.Message {
	mi := &file_C2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2Update.ProtoReflect.Descriptor instead.
func (*C2Update) Descriptor() ([]byte, []int) {
	return file_C2_proto_rawDescGZIP(), []int{1}
}

func (x *C2Update) GetMalwareId() string {
	if x != nil {
		return x.MalwareId
	}
	return ""
}

func (x *C2Update) GetVictims() []*VictimStatus {
	if x != nil {
		return x.Victims
	}
	return nil
}

func (x *C2Update) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_C2_proto protoreflect.FileDescriptor

var file_C2_proto_rawDesc = []byte{
	0x0a, 0x08, 0x43, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x43, 0x32, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x64, 0x0a, 0x0c, 0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x64,
	0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x43, 0x32, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6c, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6c, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64,
	0x12, 0x2a, 0x0a, 0x07, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x43, 0x32, 0x2e, 0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x07, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x73, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_C2_proto_rawDescOnce sync.Once
	file_C2_proto_rawDescData = file_C2_proto_rawDesc
)

func file_C2_proto_rawDescGZIP() []byte {
	file_C2_proto_rawDescOnce.Do(func() {
		file_C2_proto_rawDescData = protoimpl.X.CompressGZIP(file_C2_proto_rawDescData)
	})
	return file_C2_proto_rawDescData
}

var file_C2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_C2_proto_goTypes = []interface{}{
	(*VictimStatus)(nil),        // 0: C2.VictimStatus
	(*C2Update)(nil),            // 1: C2.C2Update
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_C2_proto_depIdxs = []int32{
	2, // 0: C2.VictimStatus.lastHeardFrom:type_name -> google.protobuf.Timestamp
	0, // 1: C2.C2Update.victims:type_name -> C2.VictimStatus
	2, // 2: C2.C2Update.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_C2_proto_init() }
func file_C2_proto_init() {
	if File_C2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_C2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VictimStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_C2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_C2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_C2_proto_goTypes,
		DependencyIndexes: file_C2_proto_depIdxs,
		MessageInfos:      file_C2_proto_msgTypes,
	}.Build()
	File_C2_proto = out.File
	file_C2_proto_rawDesc = nil
	file_C2_proto_goTypes = nil
	file_C2_proto_depIdxs = nil
}
